// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/movie/:id": {
    params: {
      "id": string;
    };
  };
  "/people/:id": {
    params: {
      "id": string;
    };
  };
  "/search": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/movie/:id" | "/people/:id" | "/search";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/movie/:id" | "/people/:id" | "/search";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/movie.tsx": {
    id: "routes/movie";
    page: "/movie/:id";
  };
  "routes/people.tsx": {
    id: "routes/people";
    page: "/people/:id";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
};